version: '3.8'
services:
  homepage-service:
    container_name: homepage
    restart: always
    image: "homepage:latest"
    networks:
      - web_network

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/homepage.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web_network
    depends_on:
      - homepage-service
networks:
  web_network:
    driver: bridge
